### ISSUE TITLE
bad bot

### ISSUE THREAD

**Issue by SunburntRock89** [KingDGrizzle/Vlag-Bot#27]
**Command Name:**Entire Bot

**Command Aliases:**bot

**Command Output:** i thought this was an issue (State if it should be an embed, and if yes, with what color in the format of `0xFFFFFF`)

**Further Details:**

- [ tick ] Maintainer Only
- [ tick ] Contains a custom emoji
- [ tick ] Contains images (place links under `Further Details`)

**Comment by KingDGrizzle** [comment]
What are you, fucking gay? - iDubbbzTV sometime in 20xx
