### ISSUE TITLE
Stock image

### ISSUE THREAD

**Issue by SunburntRock89** [KingDGrizzle/Vlag-Bot#28]
**Command Name:** -stock

**Command Aliases:** 

**Command Output:** Sends a stock image, I'm sure there's a package for that

**Further Details:**
N/A

**Comment by KingDGrizzle** [comment]
Why don't u research if there is a package for stock images :D

**Comment by SunburntRock89** [comment]
lmao will do

**Comment by dragonfart99** [comment]
...

**Comment by KingDGrizzle** [comment]
?

**Comment by SunburntRock89** [comment]
please stop I got that in my email

**Comment by KingDGrizzle** [comment]
https://i.kingdgrizzle.ml/2017/11/O935D9.png
